apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: /mnt/exports/asb
    server: 192.168.10.5
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: default
    name: pv01-ref 
